---
title: "Marketer Tool"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: ["menu"]
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(dplyr)
library(highcharter)
library(openintro)
library(plotly)
library(ggplot2)
library(rpivotTable)
library(DT)
library(data.table)
library(tidyr)
library(ggplot2)
library(clValid)
library(dbscan)
library("NbClust")
library(fpc)
library("magrittr")
library(shiny)
library("cluster")
library("clustertend")
library("factoextra")
```

```{r}
#Data
data <- fread('../data.csv')
```

```{r}
### Data Cleaning
df_data <- data %>% 
  mutate(Quantity = replace(Quantity, Quantity<=0, NA),
         UnitPrice = replace(UnitPrice, UnitPrice<=0, NA))

df_data <- df_data %>%
  drop_na()
```

```{r}
mycolors <- c("blue","#FFC125","darkgreen","darkorange")
```

```{r include=FALSE}
### Recode variables
#We should do some recoding and convert character variables to factors.

df_data <- df_data %>% 
  mutate(InvoiceNo=as.factor(InvoiceNo), StockCode=as.factor(StockCode), 
         InvoiceDate=as.Date(InvoiceDate, '%m/%d/%Y %H:%M'), CustomerID=as.factor(CustomerID), 
         Country=as.factor(Country))

df_data <- df_data %>% 
  mutate(total_dolar = Quantity*UnitPrice)

glimpse(df_data)
```

```{r include=FALSE}
#RFM
df_RFM <- df_data %>% 
  group_by(CustomerID) %>% 
  summarise(recency=as.numeric(as.Date("2012-01-01")-max(InvoiceDate)),
            frequenci=n_distinct(InvoiceNo), monitery= sum(total_dolar)/n_distinct(InvoiceNo)) 

```

```{r include=FALSE}
#scale dataframe
df_RFM2 <- df_RFM[1:4]
row.names(df_RFM2) <- df_RFM2$CustomerID
df_RFM2$CustomerID <- NULL

df_RFM2 <- scale(df_RFM2,scale = TRUE)
summary(df_RFM2)
```




Interactive Data Visualisation
============================================

Row
--------------------------------------------

###Customer Analysis

```{r}
valueBox(paste("Sales"),
         color = "warning")
```

###Number of Customers

```{r}
tmp <- aggregate(.~CustomerID, df_data, FUN=head, 1)
valueBox(round(nrow(tmp),digits = 2),
         icon = "fa-user")
```


###Average Sale per Customer

```{r}
df_data$sales = df_data$UnitPrice*df_data$Quantity
tmp <- df_data %>% group_by(CustomerID) %>% summarise(meansales = mean(sales))
tmp <- round(mean(tmp$meansales), digits = 2)
valueBox(tmp,
         icon = "fa-user")
```

###Average Quantity per Purchase
```{r}
tmp <- df_data %>% group_by(CustomerID, InvoiceDate) %>% summarise(number = n())
tmp <- round(mean(tmp$number), digits = 2)
valueBox(tmp,
         icon = "fa-user")
```


RFM
==========================================

Row
-------------------------------------------

#### Recency
```{r} 
hist(df_RFM$recency)
```


#### Frequency
```{r} 
hist(df_RFM$frequenci, breaks = 50)
```


#### Monetary Value
```{r} 
df_RFM$monitery <- log(df_RFM$monitery)
hist(df_RFM$monitery, breaks = 50)
```

Row
---------------------------------------

###Recency vs Frequency vs monetary value
```{r }
ggplot(df_RFM, aes(x=df_RFM$recency, y=df_RFM$frequenci, size=df_RFM$monitery)) + geom_point(alpha=0.2)

#plot1 <- plot_ly(df_RFM, x = ~df_RFM$recency, y = ~df_RFM$frequenci, type="scatter", text = paste("Clarity: ", df_RFM$monitery), mode = "markers", color = ~df_RFM$monitery, size = ~df_RFM$monitery)
#plot1
```


Clustering Analysis
==============================================

Row
-------------------------------------------

###Optimal number of clusters
```{r}
set.seed(123)
#gapstat.res <- fviz_nbclust(df_RFM2, kmeans, nstart = 25,  method = "gap_stat", nboot = 500)+ labs(subtitle = "Gap statistic method")
#gapstat.res
#nbclust.res <- NbClust(data = df_RFM2, diss = NULL, distance = "euclidean", min.nc = 2, max.nc = 15, method = kmeans)
#nbclust.res
```


###Comparing clustering algorithms
```{r}
#clmethods <- c("hierarchical","kmeans","pam","fanny","clara")
#intern <- clValid(df_RFM2, nClust = 2:6, clMethods = clmethods, validation = "internal")
#summary(intern)
```


###DSBSCAN
```{r}
#DBSCAN method
set.seed(123)
dbscan.res <- fpc::dbscan(df_RFM2, eps = 0.15, MinPts = 5)
head(dbscan.res$cluster)
print.dbscan(dbscan.res)#zero is outlier

fviz_cluster(dbscan.res, data = df_RFM2, stand = FALSE, #to visualize, with black is outlier
             ellipse = FALSE, show.clust.cent = FALSE,
             geom = "point",palette = "jco", ggtheme = theme_classic())
```


Row
----------------------------------------

###Cluster plot

```{r}

clara.res <- clara(df_RFM2, 3, metric = "euclidean", stand = FALSE, samples = 50, pamLike = FALSE)#CLARA as example

#ddf_RFM <- cbind(df_RFM2, cluster = clara.res$cluster)#to implement the clusters

fviz_cluster(clara.res , data = df_RFM2,
             ellipse.type = "convex",
             palette = "jco",
             ggtheme = theme_minimal())#visualize clara
```


Recommendations
=========================================





Authors
========================================







